# This file was generated by GoReleaser. DO NOT EDIT.
cask "chainsaw" do
  version "0.5.0-SNAPSHOT-cbb5c0c"

  on_macos do
    on_intel do
      sha256 "29d3ee796cfdd78caf8e86aee0f0b0d8427f85f5976684634d071792138b833b"
      url "https://github.com/jessequinn/chainsaw-cli/releases/download/v0.5.0/chainsaw_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b09b42e30e4176edce23686661a284db5b3223e66560bee9703537a6c410bc71"
      url "https://github.com/jessequinn/chainsaw-cli/releases/download/v0.5.0/chainsaw_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c679cc55752052e94d7535df92f8694280ee17efb09d1f414931910a5243676"
      url "https://github.com/jessequinn/chainsaw-cli/releases/download/v0.5.0/chainsaw_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a16b28d8358fcd4103b7066ff20daff1facb07e156a878a37b0e8defbdee6304"
      url "https://github.com/jessequinn/chainsaw-cli/releases/download/v0.5.0/chainsaw_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chainsaw"
  desc "Supply chain security scanner for CRA compliance"
  homepage "https://github.com/jessequinn/chainsaw-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chainsaw"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chainsaw"]
    end
  end
  generate_completions_from_executable "bin/chainsaw", "completion",
    shell_parameter_format: :cobra

  # No zap stanza required

end
