# This file was generated by GoReleaser. DO NOT EDIT.
cask "chainsaw-cli" do
  head "https://github.com/jessequinn/chainsaw-cli.git", branch: "main"

  version "0.5.0-SNAPSHOT-f8c9598"

  on_macos do
    on_intel do
      sha256 "6a9b1d8e87c88e766f56157ead8eb16205b51fd1a92c37bfdc0bda3cccb58cc8"
      url "https://github.com/jessequinn/chainsaw-cli/releases/download/v0.5.0/chainsaw_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "25685d42615c3d9cb627ef0330e017d6e4d659dbf7b446407e70caf1cee51959"
      url "https://github.com/jessequinn/chainsaw-cli/releases/download/v0.5.0/chainsaw_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e6eacf34abd903d7fa95799be541bba7c164332c971f29457c06e0e5a89b7059"
      url "https://github.com/jessequinn/chainsaw-cli/releases/download/v0.5.0/chainsaw_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa32870ba944589926106da09629a3f1fb6fe9dff7e0ec04e54f4fcf35ebb4a9"
      url "https://github.com/jessequinn/chainsaw-cli/releases/download/v0.5.0/chainsaw_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chainsaw"
  desc "Supply chain security scanner for CRA compliance"
  homepage "https://github.com/jessequinn/chainsaw-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chainsaw"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chainsaw"]
    end
  end
  generate_completions_from_executable "bin/chainsaw", "completion",
    shell_parameter_format: :cobra

  # No zap stanza required

end
