# This file was generated by GoReleaser. DO NOT EDIT.
cask "chainsaw-cli" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "7755611fb311d838af670ce98c04a048ea9c0d6bd90545af0fc8c566127a908c"
      url "https://github.com/jessequinn/chainsaw-cli/releases/download/v#{version}/chainsaw_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f36310eac6a1c3cad56d28e490b018e330810dd42bbf9254086b8629338dc157"
      url "https://github.com/jessequinn/chainsaw-cli/releases/download/v#{version}/chainsaw_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "74efdcca00e519a3ec0be8191b23f54e387d26575b30ebf086e9f582fbdbd2b0"
      url "https://github.com/jessequinn/chainsaw-cli/releases/download/v#{version}/chainsaw_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b51f530d8a6f4afdd64b134b77f735806cc7c84c3fae89a8aeab433b86df1783"
      url "https://github.com/jessequinn/chainsaw-cli/releases/download/v#{version}/chainsaw_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chainsaw-cli"
  desc "Supply chain security scanner for CRA compliance"
  homepage "https://github.com/jessequinn/chainsaw-cli"

  binary "chainsaw"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chainsaw"]
    end
  end

  # No zap stanza required
end
